"""empty message

Revision ID: d92a1d3b358a
Revises: 15cc2d0a4efd
Create Date: 2018-04-11 20:56:38.756708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd92a1d3b358a'
down_revision = '15cc2d0a4efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('blog', 'contend')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('contend', mysql.TEXT(), nullable=False))
    op.drop_column('blog', 'content')
    # ### end Alembic commands ###
